title: WebShop
description: Towards Scalable Real-World Web Interaction with Grounded Language Agents
env_repo: https://github.com/princeton-nlp/WebShop
mdl_repo: # To do
paper: https://arxiv.org/abs/2207.01206
twitter:
    username: princeton_nlp
    title_image: https://avatars.githubusercontent.com/u/44678448?s=280&v=4
authors:
    - name: Shunyu Yao
      link: https://ysymyth.github.io/
      pic: https://ysymyth.github.io/images/self.jpeg
    - name: Howard Chen
      link: https://howard50b.github.io/
      pic: https://media-exp2.licdn.com/dms/image/C4E03AQFJvzNyu9Y0ZA/profile-displayphoto-shrink_200_200/0/1516499453606?e=1661385600&v=beta&t=ttflKId8nMSQjLUDC28zuAtMoDoXW77MxAfRptuWagI
    - name: John Yang
      link: https://john-b-yang.github.io/
      pic: https://drive.google.com/uc?export=view&id=1ocEEB27CCtYQu0kLDFGZqwW7Lh4eswwQ
    - name: Karthik Narasimhan
      link: https://www.cs.princeton.edu/~karthikn/
      pic: https://princeton-nlp.github.io/assets/images/people/karthik-photo.jpg